### ISSUE TITLE
Berechnung Te

### ISSUE THREAD

**Issue by alexandrawelp** [marving1405/Bachelorarbeit-Thermodynamik#2]
Was steckt hinter der Gleichung Zeile 113?
Ich vermute, dass dir da Klammern im Nenner fehlen. Was genau ist Te? Woher kommt Tmittel_h?

**Comment by marving1405** [comment]
Te ist die "Excess temperature of wall", die ich über die zugeführte Wärme berechne. Wird für die Funktion alpha_boiling berechnet.
Tmittel_H ist eine Annahme für die heiße Temperatur des Speicherfluides für Wärmeübertrager 2 (x=0 bis x=1). Da wird dann weiter unten die Länge des WÜ berechnet.

**Comment by alexandrawelp** [comment]
Was ist die 15? Weiterhin glaub ich, dass da Klammern fehlen

**Comment by marving1405** [comment]
Bekomme trotz geänderter Klammersetzung und Vergrößerung der Länge des WÜs noch zu hohe Temperaturen raus. Da muss ich nochmal schauen.

**Comment by alexandrawelp** [comment]
In deiner Rechnung müsstest du eigentlich wieder die logarithmische Mitteltemperatur einsetzen. Aber da kommst du auf direktem Wege nicht dran. Setz dein Te erstmal gleich Tfluid, dann ist dein dpsat gleich 0 und schau, ob das damit durchläuft.

**Comment by marving1405** [comment]
Alles klar, das probiere ich mal aus.

**Comment by marving1405** [comment]
Ich kann dir dann nochmal sagen, wie groß der Wert für das alpha ist, ob das dann halbwegs realistisch ist

**Comment by marving1405** [comment]
Programm läuft mit dPSat = 0 durch
