### ISSUE TITLE
Fehler in Berechnung der mittleren logarithmischen Temperaturdifferenz

### ISSUE THREAD

**Issue by alexandrawelp** [marving1405/Bachelorarbeit-Thermodynamik#3]
Du verwendest bei dir immer deltaT_Fluid 1 und delta_T_fluid2. Genutzt werden muss aber delta_T_eintritt und austritt. Schau dir nochmal den Link an, den ich dir geschickt hab

https://www.thermal-engineering.org/de/was-ist-die-logarithmische-mittlere-temperaturdifferenz-lmtd-definition/

**Comment by marving1405** [comment]
In allen WÜ behoben
