### ISSUE TITLE
Ist es ein Kreisprozess, wenn Zustand 1 ungleich Zustand 4?

### ISSUE THREAD

**Issue by alexandrawelp** [marving1405/Bachelorarbeit-Thermodynamik#4]
Bitte drüber nachdenken

**Comment by marving1405** [comment]
Was meinst du hierbei genau? Zustand 4 muss doch ungleich Zustand 1 sein. Der Druck ist gleich, aber die Temperatur nicht. Oder hat sich das schon bei unserem Gespräch erledigt? @purplechickpea

**Comment by alexandrawelp** [comment]
Mein Fehler, ich habe mich vertan, als ich deinen Code durchgeschaut habe!
