### ISSUE TITLE
T3 sinkt mit steigender Speichertemperaturdifferenz

### ISSUE THREAD

**Issue by marving1405** [marving1405/Bachelorarbeit-Thermodynamik#5]
Wenn ich meine Differenz zwischen Thoch_H und Thoch_L weiter vergrößere, wird mein T3 immer kleiner. Dadurch stimmt die Nettoleistung auch nicht mehr (siehe Plot)
Ich kann keinen Fehler finden.
Ab Zeile 138 WÜ3 @purplechickpea

**Comment by alexandrawelp** [comment]
Zeile 142: dein dTA_3 müsste doch T_hoch_L - T_sattdampf2 sein?

**Comment by marving1405** [comment]
Hab ich probiert. Geht auch nicht. Jedoch müsste mein dTA doch die Differenz der beiden Fluide im Eintritt des WÜ sein? Gleiches für den Austritt.
Also dTA = Thoch_H - T2_Sattdampf und dTB = Thoch_L - T3.
Das T3 berechnet er ja in der Funktion test_fsolve.

**Comment by alexandrawelp** [comment]
Du nimmst immer die Temperaturdifferenzen "links" und "rechts". Das heißt bei einem Gegenstromwärmeübertrager paarst du Austrittstemperatur mit Eintrittstemperatur

**Comment by marving1405** [comment]
Stimmt, das habe ich außer Acht gelassen. Hab ich geändert.
Geht komischerweise immer noch nicht. Es scheint mir so, als wäre irgendwo ein Bruch falsch herum gedreht, weil alles was zur T3 Vergrößerung führen sollte, führt jedoch zu einer Verkleinerung

**Comment by alexandrawelp** [comment]
Füg mal ein zusätzliches Minus im Funktionsaufruf bei solveT3 ein. Du musst -Q nutzen, da du Q für die Bilanz des Öls betrachtet hast und jetzt dein Arbeitsfluid betrachtest. Was beim Öl "rausgeht", muss ja beim Arbeitsfluid "rein".
Was du auch noch machen solltest, ist dir einen Zustand mal von Hand auszurechnen (muss nicht super genau sein, ein Überschlag reicht, du kannst auch Excel benutzen), damit du dir sicher sein kannst, dass das Programm wirklich das rechnet, was es soll

**Comment by marving1405** [comment]
Alles klar, probiere ich später mal aus.

**Comment by marving1405** [comment]
Funktioniert jetzt
